language: scala

scala:
- 2.12.2

jdk:
- oraclejdk8

env:
  global:
    secure: AlfewbTHVv6Mzg/f4bK75xAKlFymXrCcEGyj4We3/w7lgHdF94vvFr/LC2HtD0dcgFkKptQOBcypZ4QmQbbv0KUCZh1YS/nKRvjISqnicLOHf6RcrpAOnRsXiXmicSsWHVToagl2OqWuHJzKEeAPIaljh+XSz+CTla3i4eXc2KADsVw+3NYoqEnz73wmGOOBkJJGd5jriHYUsHdhBVo/RfPwYTk5Xhqw4djT4XpamB0a4tQn0n2LNhm5lHRu9xs4kpCjWZPZRaSw2yKDsh+5MeFhDamLASMMYqSuv5a/kg+WdYPIpPURUppQSlpkY35ja8WMkK0TYYcNBgxWsmVrhm6RTOx3aQ9ZEzRlmEtBE/y4fCfCV3al5rXPv834z6EMw/S9KDEBFZ1SWKKozxjOqes1xxjqO3rZqsmbsSok1R5EcL3SS/8fIcvFjaYvKE2e4vKTqJastSSWXuGEIKFHXjRf6e6zJ/QL+849PI+M40OytCzZS6Pjj/t27p4s4cEAb6VjZ+yaT1Q47BuJtLT2RfXVfITmIrD2+JC0fDDhaBzPFVNHONN0hXXExSyA/EuDk5iRaW7vlO6k/Kx288QxivLkO6NvTIY/kf7NrMnLjky9QI9wGZB45bDeJJg213LL41WiyBfQGtPo4gsHLRWQy/LVpnlF4LQEv9O5oYTPK1w=
